@echo off
REM Environment setup script for C++ development
REM Generated by auto_install_deps.py

echo Setting up C++ development environment...

REM Add MinGW-w64 to PATH
set "PATH=C:\Users\Administrator\c++_deps\mingw64\bin;%PATH%"

REM Add CMake to PATH
set "PATH=C:\Users\Administrator\c++_deps\cmake\bin;%PATH%"

REM Add Ninja to PATH
set "PATH=C:\Users\Administrator\c++_deps\ninja;%PATH%"

REM Set environment variables
set "BOOST_ROOT=C:\Users\Administrator\c++_deps\boost"
set "EIGEN3_ROOT=C:\Users\Administrator\c++_deps\eigen"
set "OpenCV_DIR=C:\Users\Administrator\c++_deps\opencv"

echo Environment variables set successfully!
echo.
echo Available tools:
gcc --version
cmake --version
ninja --version

echo.
echo Environment setup complete!
pause
